version: '3.8'
services:
  db:
    image: postgres:14.3-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db_vetcenter
    ports:
      - '5435:5432'
#    volumes:
#      - db:/var/lib/postgresql/data